// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_model.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_model.g.dart';

@freezed
class UserModel with _$UserModel {
  factory UserModel({required Data data}) = _UserModel;
  factory UserModel.fromJson(Map<String, dynamic> json) => _$UserModelFromJson(json);
}

@freezed
class Data with _$Data {
  factory Data(
      {required String name,
        required String email,
        required String photo,
        required String role,
        required DateTime createdAt,
        required DateTime updatedAt,
        required String id}) = _data;

  factory Data.fromJson(Map<String, dynamic> json) => _$DataFromJson(json);
}