const DEVELOPMENT_BASE_URL = "http://localhost:3000";
const DEVELOPMENT_API_BASE_URL = `${DEVELOPMENT_BASE_URL}/api/v1`;

export const SERVER_BASE_URL = DEVELOPMENT_BASE_URL;
export const API_BASE_URL = DEVELOPMENT_API_BASE_URL;
