const DEVELOPMENT_BASE_URL = "";
const DEVELOPMENT_API_BASE_URL = `${DEVELOPMENT_BASE_URL}/api`;

export const SERVER_BASE_URL = DEVELOPMENT_BASE_URL;
export const API_BASE_URL = DEVELOPMENT_API_BASE_URL;
